/**
 * Top 200+ Biohacking Supplements for Automated Content Generation
 */

export const BIOHACKING_SUPPLEMENTS = [
  // Energy & Performance (20)
  'Creatine Monohydrate',
  'Beta-Alanine',
  'L-Carnitine',
  'Acetyl-L-Carnitine (ALCAR)',
  'Cordyceps Mushroom',
  'Rhodiola Rosea',
  'Ashwagandha',
  'Maca Root',
  'Ginseng (Panax)',
  'Coenzyme Q10 (CoQ10)',
  'PQQ (Pyrroloquinoline Quinone)',
  'D-Ribose',
  'Citrulline Malate',
  'Beetroot Extract',
  'Iron (for athletes)',
  'B-Complex Vitamins',
  'Caffeine + L-Theanine',
  'Guarana',
  'Taurine',
  'Alpha-GPC',

  // Muscle Building & Recovery (25)
  'Whey Protein Isolate',
  'Casein Protein',
  'BCAAs (Branched-Chain Amino Acids)',
  'EAAs (Essential Amino Acids)',
  'L-Glutamine',
  'HMB (Beta-Hydroxy Beta-Methylbutyrate)',
  'Collagen Peptides',
  'Glucosamine Sulfate',
  'Chondroitin',
  'MSM (Methylsulfonylmethane)',
  'Curcumin (Turmeric Extract)',
  'Boswellia Serrata',
  'Omega-3 Fish Oil',
  'Krill Oil',
  'Magnesium Glycinate',
  'Zinc Picolinate',
  'Vitamin D3 + K2',
  'Tart Cherry Extract',
  'Bromelain',
  'Proteolytic Enzymes',
  'CBD Oil (for recovery)',
  'Electrolyte Powder',
  'Sodium Bicarbonate',
  'Glycine',
  'Bone Broth Protein',

  // Cognitive Enhancement (30)
  'Lions Mane Mushroom',
  'Bacopa Monnieri',
  'Ginkgo Biloba',
  'Phosphatidylserine',
  'Huperzine A',
  'Alpha-Lipoic Acid',
  'NAC (N-Acetyl Cysteine)',
  'L-Tyrosine',
  'L-Phenylalanine',
  'DHA (Docosahexaenoic Acid)',
  'Choline (CDP-Choline or Alpha-GPC)',
  'Uridine Monophosphate',
  'Phenylpiracetam',
  'Noopept',
  'Aniracetam',
  'Oxiracetam',
  'Piracetam',
  'Sulbutiamine',
  'Vinpocetine',
  'Mucuna Pruriens',
  'SAMe (S-Adenosyl Methionine)',
  'DMAE (Dimethylaminoethanol)',
  'Gotu Kola',
  'Forskolin',
  'Artichoke Extract',
  'PRL-8-53',
  'Semax',
  'Selank',
  'Cerebrolysin',
  'Nicotinamide Riboside (NR)',

  // Hormonal Optimization (25)
  'Tongkat Ali (Longjack)',
  'Tribulus Terrestris',
  'Fenugreek Extract',
  'D-Aspartic Acid (DAA)',
  'Boron',
  'Shilajit',
  'Fadogia Agrestis',
  'Pine Pollen',
  'Nettle Root Extract',
  'DIM (Diindolylmethane)',
  'Chrysin',
  'Calcium D-Glucarate',
  'DHEA',
  'Pregnenolone',
  'Melatonin',
  ' 5-HTP (5-Hydroxytryptophan)',
  'L-Dopa (Mucuna)',
  'Vitex (Chasteberry)',
  'Black Cohosh',
  'Red Clover',
  'Saw Palmetto',
  'Pygeum Africanum',
  'Beta-Sitosterol',
  'Iodine (for thyroid)',
  'Selenium (for thyroid)',

  // Gut Health & Digestion (20)
  'Probiotics (Multi-Strain)',
  'Prebiotics (Inulin)',
  'L-Glutamine (for gut)',
  'Zinc Carnosine',
  'DGL (Deglycyrrhizinated Licorice)',
  'Slippery Elm',
  'Marshmallow Root',
  'Digestive Enzymes',
  'Betaine HCl',
  'Apple Cider Vinegar',
  'Psyllium Husk',
  'Activated Charcoal',
  'Bentonite Clay',
  'Aloe Vera Extract',
  'Ginger Root',
  'Peppermint Oil',
  'Fennel Seed',
  'Butyrate',
  'Akkermansia Probiotic',
  'Saccharomyces Boulardii',

  // Sleep & Relaxation (20)
  'Magnesium Threonate',
  'Glycine (for sleep)',
  'L-Theanine',
  'GABA',
  'Valerian Root',
  'Passionflower',
  'Lemon Balm',
  'Chamomile Extract',
  'Lavender Oil',
  'Magnolia Bark',
  'Apigenin',
  'Tart Cherry (for melatonin)',
  'CBD + CBN (for sleep)',
  'Kava Kava',
  'Skullcap',
  'California Poppy',
  'Hops Extract',
  'Theanine + GABA combo',
  'L-Tryptophan',
  'Phosphatidylserine (for cortisol)',

  // Longevity & Anti-Aging (25)
  'NMN (Nicotinamide Mononucleotide)',
  'Resveratrol',
  'Pterostilbene',
  'Quercetin',
  'Fisetin',
  'Spermidine',
  'Astaxanthin',
  'Glutathione',
  'NAC (anti-aging)',
  'Alpha-Lipoic Acid (anti-aging)',
  'Carnosine',
  'Taurine (longevity)',
  'Glycine (longevity)',
  'Apigenin (senolytic)',
  'EGCG (Green Tea Extract)',
  'Curcumin (anti-aging)',
  'Berberine',
  'Metformin (prescription)',
  'Rapamycin (prescription)',
  'Urolithin A',
  'CA-AKG (Calcium Alpha-Ketoglutarate)',
  'TMG (Trimethylglycine)',
  'Betaine',
  'Sulforaphane (Broccoli Sprouts)',
  'Hyaluronic Acid',

  // Immune Support (20)
  'Vitamin C (high dose)',
  'Vitamin D3 (immune)',
  'Zinc (immune)',
  'Elderberry',
  'Echinacea',
  'Andrographis',
  'Astragalus',
  'Reishi Mushroom',
  'Turkey Tail Mushroom',
  'Chaga Mushroom',
  'Maitake Mushroom',
  'Beta-Glucans',
  'Colostrum',
  'Lactoferrin',
  'Olive Leaf Extract',
  'Oregano Oil',
  'Garlic Extract (Allicin)',
  'Black Seed Oil (Nigella Sativa)',
  'Monolaurin',
  'Quercetin (immune)',

  // Metabolic Health (15)
  'Berberine (blood sugar)',
  'Chromium Picolinate',
  'Cinnamon Extract',
  'Bitter Melon',
  'Gymnema Sylvestre',
  'Alpha-Lipoic Acid (glucose)',
  'Inositol',
  'Vanadyl Sulfate',
  'Banaba Leaf',
  'White Mulberry Leaf',
  'CLA (Conjugated Linoleic Acid)',
  'L-Carnitine (fat loss)',
  'Green Coffee Bean Extract',
  'Garcinia Cambogia',
  'Forskolin (fat loss)',

  // Peptides (25)
  'BPC-157',
  'TB-500 (Thymosin Beta-4)',
  'GHK-Cu (Copper Peptide)',
  'Ipamorelin',
  'CJC-1295',
  'Sermorelin',
  'Tesamorelin',
  'Hexarelin',
  'GHRP-2',
  'GHRP-6',
  'AOD-9604',
  'Melanotan II',
  'PT-141 (Bremelanotide)',
  'Selank',
  'Semax',
  'Epithalon (Epitalon)',
  'Thymosin Alpha-1',
  'LL-37 (Antimicrobial Peptide)',
  'Dihexa',
  'P21 (Cerebrolysin derivative)',
  'NA-Selank',
  'NA-Semax',
  'Pinealon',
  'Cortagen',
  'Pentadecapeptide BPC-157',
];

export const TOTAL_SUPPLEMENTS = BIOHACKING_SUPPLEMENTS.length;

export function getNextSupplement(lastIndex = -1) {
  const nextIndex = (lastIndex + 1) % BIOHACKING_SUPPLEMENTS.length;
  return BIOHACKING_SUPPLEMENTS[nextIndex];
}

export function getSupplementByIndex(index) {
  return BIOHACKING_SUPPLEMENTS[index % BIOHACKING_SUPPLEMENTS.length];
}
